### ISSUE TITLE
System check says: File integrity check failed 

### ISSUE THREAD

**Issue by jnachtigall** [piwik/piwik-package#16]
Go to settings => System check.

```
File integrity 	

File integrity check failed and reported some errors. This is most likely due to a partial or failed upload of some of the Piwik files. You should reupload all the Piwik files in BINARY mode and refresh this page until it shows no error.
```

**Comment by aureq** [comment]
Hi @jnachtigall 

there has been a huge rewrite in the way the manifest.inc.php is generate. Rather than using the official one, I use the same code and also correctly remap files that are in /etc/piwik/ to config/
I also generate md5sums on the fly so everything stays consistent and fairly safe.

This new mechanism will also help us in the future should we need to update/modify more files for any reasons.

**Comment by Viswan-piwki** [comment]
HI there,
i get this error File integrity

File integrity check failed and reported some errors. This is most likely due to a partial or failed upload of some of the Piwik files. You should reupload all the Piwik files in BINARY mode and refresh this page until it shows no error.
File size mismatch: /apps/bweb/servers/apache-2.2.20/htdocs/piwik/misc/cron/archive.sh (expected length: 3996, found: 3994)

**Comment by aureq** [comment]
Hi

From the look of the details you've provided, this is not related to the Debian Package.
What I would recommend is to manually download the archive for the matching version and check for any differences.

**Comment by Viswan-piwki** [comment]
Thanks for swift reply. I have old piwik version, if you mean download 1.1.2 version and then compare the files?

Regards,
Viswa

**Comment by Viswan-piwki** [comment]
Also advice on this please?

Piwik is set for confluence. For march month it shows only 19 visits and 23 page views. Im sure this is wrong. Ours confluence is huge and im pretty sure there should be more. We have around 20k users using our confluence. Does file integrity is related to this ?

**Comment by aureq** [comment]
@Viswan-piwki 

* yes compare the files from the original archive and understand the differences.
* from what I understand, Piwik will not prevent data collection even if a give file has a different checksum.
* the file referenced is in charge of the archiving process which is meant to be run through a scheduled task. Nothing to do with live data acquisition. So if your stats aren't getting through, you should further investigate in your environment to understand why data isn't collected.

**Comment by Viswan-piwki** [comment]
Hi there,
One more query. I have permissioned 777 to piwik folder and also restarted apache. But it still does not give me option to choose auto-update version? Both /tmp and /misc have write permissions. I tried the manual upgrade and having restarted the piwik, the page returned blank

And also do i have to copy the old config.ini.php to new piwik. ? i did not do that. I uploaded the new piwik files to web server folder (where old one was) and restarted the apache

**Comment by Viswan-piwki** [comment]
I have sorted now the integrity. However my evolution graph is showing red (negative). 
And for other application JIRA, i'm not able to choose dates. Previous months and years are not displayed in the drop down. Thus showing March data as 0%

**Comment by aureq** [comment]
@Viswan-piwki Unfortunately, we cannot debug every single issue through Github. The best suggestion I have to offer would be to contact @mattab through their professional services at https://piwik.pro/
The guys there should be able to support you and even help you migrate to a more recent version of Piwik.
