### ISSUE TITLE
Debian package for 2.12.1

### ISSUE THREAD

**Issue by mattab** [piwik/piwik-package#28]
Hi @aureq!

Piwik 2.12.1 will be released in couple hours, this will be an excellent stable version of Piwik - could we release the Debian package for letting the community use the very best Piwik has to offer?

**Comment by aureq** [comment]
Hi @mattab 

Done since last night ;-) I need to find a way to automate most of this whenever this is possible.
With my latest changes, we are progressing in the right direction which also give us access to a new repos named "sunrise" (rc) and "eclipse" (beta).

So early adopters would have access to the latest features in almost near real-time.

**Comment by mattab** [comment]
That's great news @aureq  :-)
