### ISSUE TITLE
Debian folder permissions wrong after each update

### ISSUE THREAD

**Issue by MagicFab** [piwik/piwik-package#36]
Oringinally reported in https://github.com/piwik/piwik/issues/8532:
 
After every debian piwik package update I always should apply manually
chown -R piwik:piwik /usr/share/piwik/tmp/

when Piwik runas as piwik user

It's changing somehow to www-data user.

**Comment by aureq** [comment]
@MagicFab this is an expected behaviour...
All Piwik files (through the debian package) are installed by default as `root:root` for security reasons.

Though, as it's a web application, the default user to run a web server is `www-data` under debian/ubuntu definitions. And as Piwik has needs to write in few folders, the post-installation tries to ensure the application stays functional.

**Comment by luckyraul** [comment]
That's ok for one time during install, but not for every package update.

**Comment by Reiner030** [comment]
phpmyadmin package uses this in postinst script:
````
        if ! dpkg-statoverride --list /var/lib/phpmyadmin/tmp >/dev/null; then
                chown -R www-data:www-data    /var/lib/phpmyadmin/tmp
        fi
````
which should be no problem for a tmp folder for piwik, too ;)
